name: Publish on Docker Hub and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
   build_and_pub:
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to docker.io
        run:  docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{secrets.DOCKER_PWD}}
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME .
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME
   deploy:
    needs: [build_and_pub]
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d
